github:
  # Token will be loaded from environment variable GITHUB_TOKEN
  token_env_var: "GITHUB_TOKEN"
  api_version: "2022-11-28"
  # Default number of days to look back for activity
  activity_lookback_days: 1
  # Types of activities to track
  activity_types:
    - commits
    - pull_requests
    - reviews
    - issues
  # Maximum number of items to fetch per type
  max_items_per_type: 50
