collect_user_update_task:
  description: >
    Collect the user's standup update through natural conversation. Tasks include:
    1. Initiate a conversation to gather accomplishments, blockers, and plans.
    2. Extract structured updates from user responses.
    3. Maintain a conversational and user-friendly tone throughout.
  expected_output: >
    A structured representation of the user's standup update, including:
    - Accomplishments
    - Blockers
    - Plans
  agent: chat_manager

fetch_github_activity_task:
  description: >
    Fetch and summarize the user's recent GitHub activity. Tasks include:
    1. Use the `github_activity` tool to gather recent commits, pull requests, and reviews.
    2. Analyze activity to identify accomplishments, ongoing work, and blockers.
  expected_output: >
    A summary of the user's GitHub activity, including:
    - Accomplishments
    - Ongoing work
    - Identified blockers
  agent: github_activity_agent

draft_standup_update_task:
  description: >
    Generate a draft standup update based on the user's input and GitHub activity. Tasks include:
    1. Integrate user-provided updates with GitHub activity insights.
    2. Create a structured draft including accomplishments, blockers, and plans.
  expected_output: >
    A well-structured draft of the standup update, including:
    - Key accomplishments
    - Identified blockers
    - Planned next steps
  agent: draft_agent