draft_standup_update_task:
  description: >
    Create an initial standup draft using GitHub data by:
    1. Structuring the GitHub activity into a standup format
    2. Highlighting key accomplishments and blockers
    3. Identifying apparent ongoing work
  expected_output: >
    A markdown-formatted draft with sections:
    - Accomplishments
    - Blockers
    - Plans
  agent: draft_agent

collect_user_update_task:
  description: >
    Refine the standup draft through user interaction by:
    1. Presenting the draft standup
    2. Asking for additional items not found in GitHub
    3. Requesting clarification on unclear items
    4. Confirming the completeness of all sections
  expected_output: >
    A final markdown-formatted standup update that includes:
    - Verified accomplishments
    - Confirmed blockers with context
    - Specific plans for the next day
  agent: user_update_agent
  human_input: true

fetch_github_activity_task:
  description: >
    Fetch and analyze recent GitHub activity by:
    1. Using the GitHub activity tool to gather recent activity
    2. Analyzing and categorizing activities into:
       - Completed work (merged PRs, closed issues)
       - Work in progress (open PRs, active issues)
       - Potential blockers (stalled PRs, blocking issues)
  expected_output: >
    A structured JSON summary containing:
    - completed_work: a list of completed items with links
    - work_in_progress: a list of ongoing items with status
    - potential_blockers: a list of items needing attention
  agent: github_activity_agent
