fetch_github_activity_task:
  description: >
    Collect and categorize recent GitHub activity by:
    1. Fetching concrete GitHub data from the last 24 hours
    2. Categorizing only verified activities:
       - Merged PRs and closed issues as completed work
       - Open PRs and active issues as work in progress
       - Issues marked as blocking or stalled PRs as blockers
    3. Including direct links to all referenced items
  expected_output: >
    A structured JSON containing only verified GitHub activities:
    - completed_work: [{title, url, type, timestamp}]
    - work_in_progress: [{title, url, type, status, last_updated}]
    - blockers: [{title, url, type, reason}]
  agent: github_activity_agent

draft_standup_update_task:
  description: >
    Create a structured standup draft using only verified GitHub data by:
    1. Converting the GitHub activity JSON into a clear standup format
    2. Using bullet points for each item with links
    3. Marking items that need user verification with [?]
    4. Not adding any speculative content
  expected_output: >
    A markdown-formatted draft with:
    - Accomplishments: Bullet points of completed work with links
    - Blockers: List of identified blocking issues
    - Plans: List of in-progress work
    Each section should only contain items from GitHub data
  agent: draft_agent

collect_user_update_task:
  description: >
    Validate and finalize the standup draft through focused user interaction:
    1. Present the current draft clearly
    2. Ask for specific corrections or additions
    3. If user expresses satisfaction (e.g., "looks good", "that's correct"), 
       conclude immediately
    4. Otherwise, ask targeted questions about unclear [?] items
    5. Limit to max 3 interactions
  expected_output: >
    A final markdown-formatted standup with:
    - User-verified accomplishments with links
    - Confirmed or added blockers
    - Specific, user-confirmed plans
    All content must come from either GitHub data or direct user input
  agent: user_update_agent
